### ISSUE TITLE
Adding Pet Pictures

### ISSUE THREAD

**Issue by JaysonRice** [JaysonRice/pets-please#4]
As a user, I should be able to add pictures of my pet that go to a main feed of pet pictures.

### Acceptance Criteria

While looking at the user's pets area on the left of the dashboard, there should be a button on individual pet cards that allow a user to add a picture of that pet.

After clicking the button, the user chooses a file from their local machine to upload. This photo should immediately be rendered onto the main pet feed in the middle of the dashboard, along with the pet and owner's names.

**Comment by AdamSpannbauer** [comment]
Hello, yes, I'd like to post pet pictures like this.  Will I be able to link to a picture online or will only upload from local machine be allowed?

Potential example image URL (pictured below): 

[`https://github.com/AdamSpannbauer/cv_intro/blob/master/data/catdog.jpg?raw=true`](https://github.com/AdamSpannbauer/cv_intro/blob/master/data/catdog.jpg?raw=true)

<p align='center'>
  <img src='https://github.com/AdamSpannbauer/cv_intro/blob/master/data/catdog.jpg?raw=true' width=50%>
</p>

**Comment by JaysonRice** [comment]
Cloudinary definitely has the capacity to upload a photo from a URL but that would currently be a stretch goal for this project after finishing the main components.
